
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141202 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser2 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public Parser2() {super();}

  /** Constructor which sets the default scanner. */
  public Parser2(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser2(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\004\000\002\003\004\000\002\004" +
    "\004\000\002\004\003\000\002\002\004\000\002\002\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\013\005\000\002" +
    "\013\005\000\002\013\005\000\002\013\005\000\002\014" +
    "\004\000\002\012\006\000\002\012\005\000\002\011\010" +
    "\000\002\011\007\000\002\010\011\000\002\006\005\000" +
    "\002\006\003\000\002\015\005\000\002\015\003\000\002" +
    "\007\003\000\002\007\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\004\022\004\001\002\000\004\005\071\001" +
    "\002\000\012\014\ufffe\015\ufffe\021\ufffe\022\ufffe\001\002" +
    "\000\004\002\070\001\002\000\012\014\022\015\015\021" +
    "\012\022\016\001\002\000\034\002\ufff9\004\ufff9\006\ufff9" +
    "\010\ufff9\011\ufff9\012\ufff9\013\ufff9\014\ufff9\015\ufff9\016" +
    "\ufff9\017\ufff9\021\ufff9\022\ufff9\001\002\000\014\002\000" +
    "\014\022\015\015\021\012\022\024\001\002\000\034\002" +
    "\uffe8\004\uffe8\006\uffe8\010\uffe8\011\uffe8\012\uffe8\013\uffe8" +
    "\014\uffe8\015\uffe8\016\uffe8\017\uffe8\021\uffe8\022\uffe8\001" +
    "\002\000\012\014\uffff\015\uffff\021\uffff\022\uffff\001\002" +
    "\000\034\002\ufff8\004\ufff8\006\ufff8\010\ufff8\011\ufff8\012" +
    "\ufff8\013\ufff8\014\ufff8\015\ufff8\016\ufff8\017\ufff8\021\ufff8" +
    "\022\ufff8\001\002\000\004\005\061\001\002\000\026\002" +
    "\uffe7\004\uffe7\005\045\012\uffe7\013\uffe7\014\uffe7\015\uffe7" +
    "\017\uffe7\021\uffe7\022\uffe7\001\002\000\034\002\ufffa\004" +
    "\ufffa\006\ufffa\010\ufffa\011\ufffa\012\ufffa\013\ufffa\014\ufffa" +
    "\015\ufffa\016\ufffa\017\ufffa\021\ufffa\022\ufffa\001\002\000" +
    "\024\002\ufffc\004\026\012\030\013\031\014\ufffc\015\ufffc" +
    "\017\027\021\ufffc\022\ufffc\001\002\000\034\002\ufffb\004" +
    "\ufffb\006\ufffb\010\ufffb\011\ufffb\012\ufffb\013\ufffb\014\ufffb" +
    "\015\ufffb\016\ufffb\017\ufffb\021\ufffb\022\ufffb\001\002\000" +
    "\012\014\022\015\015\021\012\022\024\001\002\000\034" +
    "\002\ufff7\004\ufff7\006\ufff7\010\ufff7\011\ufff7\012\ufff7\013" +
    "\ufff7\014\ufff7\015\ufff7\016\ufff7\017\ufff7\021\ufff7\022\ufff7" +
    "\001\002\000\036\002\uffe7\004\uffe7\005\036\006\uffe7\010" +
    "\uffe7\011\uffe7\012\uffe7\013\uffe7\014\uffe7\015\uffe7\016\uffe7" +
    "\017\uffe7\021\uffe7\022\uffe7\001\002\000\034\002\ufff2\004" +
    "\ufff2\006\ufff2\010\ufff2\011\ufff2\012\ufff2\013\ufff2\014\ufff2" +
    "\015\ufff2\016\ufff2\017\ufff2\021\ufff2\022\ufff2\001\002\000" +
    "\012\014\022\015\015\021\012\022\024\001\002\000\012" +
    "\014\022\015\015\021\012\022\024\001\002\000\012\014" +
    "\022\015\015\021\012\022\024\001\002\000\012\014\022" +
    "\015\015\021\012\022\024\001\002\000\034\002\ufff3\004" +
    "\ufff3\006\ufff3\010\ufff3\011\ufff3\012\ufff3\013\ufff3\014\ufff3" +
    "\015\ufff3\016\ufff3\017\ufff3\021\ufff3\022\ufff3\001\002\000" +
    "\034\002\ufff4\004\ufff4\006\ufff4\010\ufff4\011\ufff4\012\ufff4" +
    "\013\ufff4\014\ufff4\015\ufff4\016\ufff4\017\ufff4\021\ufff4\022" +
    "\ufff4\001\002\000\034\002\ufff5\004\026\006\ufff5\010\ufff5" +
    "\011\ufff5\012\030\013\031\014\ufff5\015\ufff5\016\ufff5\017" +
    "\ufff5\021\ufff5\022\ufff5\001\002\000\034\002\ufff6\004\ufff6" +
    "\006\ufff6\010\ufff6\011\ufff6\012\030\013\031\014\ufff6\015" +
    "\ufff6\016\ufff6\017\ufff6\021\ufff6\022\ufff6\001\002\000\014" +
    "\006\040\014\022\015\015\021\012\022\024\001\002\000" +
    "\004\006\044\001\002\000\034\002\ufff0\004\ufff0\006\ufff0" +
    "\010\ufff0\011\ufff0\012\ufff0\013\ufff0\014\ufff0\015\ufff0\016" +
    "\ufff0\017\ufff0\021\ufff0\022\ufff0\001\002\000\016\004\026" +
    "\006\uffeb\011\042\012\030\013\031\017\027\001\002\000" +
    "\012\014\022\015\015\021\012\022\024\001\002\000\004" +
    "\006\uffec\001\002\000\034\002\ufff1\004\ufff1\006\ufff1\010" +
    "\ufff1\011\ufff1\012\ufff1\013\ufff1\014\ufff1\015\ufff1\016\ufff1" +
    "\017\ufff1\021\ufff1\022\ufff1\001\002\000\016\006\040\014" +
    "\022\015\015\020\046\021\012\022\050\001\002\000\012" +
    "\014\022\015\015\021\012\022\024\001\002\000\004\020" +
    "\054\001\002\000\022\004\uffe7\005\036\006\uffe7\011\051" +
    "\012\uffe7\013\uffe7\017\uffe7\020\uffe9\001\002\000\004\022" +
    "\052\001\002\000\006\011\051\020\uffe9\001\002\000\004" +
    "\020\uffea\001\002\000\012\014\022\015\015\021\012\022" +
    "\024\001\002\000\014\004\026\010\056\012\030\013\031" +
    "\017\027\001\002\000\012\014\uffef\015\uffef\021\uffef\022" +
    "\uffef\001\002\000\014\004\026\010\060\012\030\013\031" +
    "\017\027\001\002\000\012\014\uffee\015\uffee\021\uffee\022" +
    "\uffee\001\002\000\012\014\022\015\015\021\012\022\024" +
    "\001\002\000\014\004\026\006\063\012\030\013\031\017" +
    "\027\001\002\000\012\014\022\015\015\021\012\022\024" +
    "\001\002\000\014\004\026\012\030\013\031\016\065\017" +
    "\027\001\002\000\012\014\022\015\015\021\012\022\024" +
    "\001\002\000\034\002\uffed\004\026\006\uffed\010\uffed\011" +
    "\uffed\012\030\013\031\014\uffed\015\uffed\016\uffed\017\027" +
    "\021\uffed\022\uffed\001\002\000\024\002\ufffd\004\026\012" +
    "\030\013\031\014\ufffd\015\ufffd\017\027\021\ufffd\022\ufffd" +
    "\001\002\000\004\002\001\001\002\000\006\020\046\022" +
    "\052\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\010\003\005\004\006\011\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\002\010\005\017\007\020\010\016\011\012\012\007\013" +
    "\013\014\022\001\001\000\002\001\001\000\016\005\066" +
    "\007\020\010\016\012\007\013\013\014\022\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\005\024\007\020\010\016" +
    "\012\007\013\013\014\022\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\005\034\007\020" +
    "\010\016\012\007\013\013\014\022\001\001\000\016\005" +
    "\033\007\020\010\016\012\007\013\013\014\022\001\001" +
    "\000\016\005\032\007\020\010\016\012\007\013\013\014" +
    "\022\001\001\000\016\005\031\007\020\010\016\012\007" +
    "\013\013\014\022\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\005\040" +
    "\006\036\007\020\010\016\012\007\013\013\014\022\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\005\040\006\042\007\020\010\016\012\007\013" +
    "\013\014\022\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\005\040\006\036\007\020\010\016\012\007\013" +
    "\013\014\022\015\046\001\001\000\016\005\056\007\020" +
    "\010\016\012\007\013\013\014\022\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\015\052\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\005\054\007\020\010" +
    "\016\012\007\013\013\014\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\005\061\007\020\010\016\012\007\013\013\014\022" +
    "\001\001\000\002\001\001\000\016\005\063\007\020\010" +
    "\016\012\007\013\013\014\022\001\001\000\002\001\001" +
    "\000\016\005\065\007\020\010\016\012\007\013\013\014" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\046\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser2$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser2$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser2$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.next_token(); 
    }


    // Connect this parser to a scanner!
    Scanner s;
    Parser2(Scanner s){ this.s=s; }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser2$actions {
  private final Parser2 parser;

  /** Constructor */
  CUP$Parser2$actions(Parser2 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser2$do_action_part00000000(
    int                        CUP$Parser2$act_num,
    java_cup.runtime.lr_parser CUP$Parser2$parser,
    java.util.Stack            CUP$Parser2$stack,
    int                        CUP$Parser2$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser2$result;

      /* select the action based on the action number */
      switch (CUP$Parser2$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= begin EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		RESULT = start_val;
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser2$parser.done_parsing();
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // begin ::= functions expr_list 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 
            System.out.println("public class Translated {\n  public static void main(String[] args) {\n " + e + "\n  }\n\n" + f + "\n}"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("begin",1, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // functions ::= functions f_def 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int fdleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String fd = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = f + "\n" + fd + "\n"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("functions",2, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // functions ::= f_def 
            {
              Object RESULT =null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String fd = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = fd + "\n";            
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("functions",2, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr_list ::= expr_list expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e1 + "    System.out.println(" + e2 + ");\n"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr_list ::= expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "    System.out.println(" + e + ");\n"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= text 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = t;      
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= if_case 
            {
              String RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = f;      
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= f_call 
            {
              String RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String fc = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = fc;     
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= act_expr 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = a;      
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= rev_expr 
            {
              String RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = r;      
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // act_expr ::= expr PLUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e1 + " + " + e2;                                     
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("act_expr",9, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // act_expr ::= expr EQUAL expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e1 + ".equals(" + e2 + ")";                          
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("act_expr",9, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // act_expr ::= expr PREFIX expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e1 + ".startsWith(" + e2 + ")";                      
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("act_expr",9, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // act_expr ::= expr SUFFIX expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "new StringBuilder(" + e1 + ").reverse().toString().startsWith(new StringBuilder(" + e2 + ").reverse().toString())"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("act_expr",9, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // rev_expr ::= REVERSE expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "new StringBuilder(" + e + ").reverse().toString()"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("rev_expr",10, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // f_call ::= ID LPAREN args RPAREN 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = i + "(" + a + ")"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("f_call",8, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // f_call ::= ID LPAREN RPAREN 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		 RESULT = i + "()";          
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("f_call",8, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // f_def ::= ID LPAREN params RPAREN_LBRACE expr RBRACE 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = " public static String " + i + "(" + p + ") {\n  return " + e + ";\n}"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("f_def",7, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // f_def ::= ID LPAREN RPAREN_LBRACE expr RBRACE 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = " public static String " + i + "() {\n  return " + e + ";\n }";          
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("f_def",7, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // if_case ::= IF LPAREN expr RPAREN expr ELSE expr 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "(" + c + "? " + t + " : " + e + ")"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("if_case",6, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // args ::= expr COMMA args 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int restright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String rest = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e + ", " + rest; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("args",4, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // args ::= expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e;               
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("args",4, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // params ::= ID COMMA params 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int restright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String rest = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "String " + p + ", " + rest; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("params",11, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // params ::= ID 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "String " + p;               
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("params",11, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // text ::= STRING 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = "\"" + s + "\""; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("text",5, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // text ::= ID 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = i;               
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("text",5, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser2$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser2$do_action(
    int                        CUP$Parser2$act_num,
    java_cup.runtime.lr_parser CUP$Parser2$parser,
    java.util.Stack            CUP$Parser2$stack,
    int                        CUP$Parser2$top)
    throws java.lang.Exception
    {
              return CUP$Parser2$do_action_part00000000(
                               CUP$Parser2$act_num,
                               CUP$Parser2$parser,
                               CUP$Parser2$stack,
                               CUP$Parser2$top);
    }
}

}
