
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACE = 5;
  public static final int NUMBER = 15;
  public static final int SEMI = 14;
  public static final int EQUAL = 13;
  public static final int PREFIX = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int IF = 11;
  public static final int ID = 16;
  public static final int ELSE = 12;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RPAREN = 4;
  public static final int SUFFIX = 9;
  public static final int LPAREN = 3;
  public static final int RBRACE = 6;
  public static final int REVERSE = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "PREFIX",
  "SUFFIX",
  "REVERSE",
  "IF",
  "ELSE",
  "EQUAL",
  "SEMI",
  "NUMBER",
  "ID"
  };
}

